export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Content-Type', 'application/json');

  return res.status(200).json({
    product: "HefestoAI",
    description: "Pre-commit code quality guardian for AI-generated code",
    faq: [
      {
        q: "What is HefestoAI?",
        a: "HefestoAI is a pre-commit guardian that detects semantic drift and risky changes in AI-generated code before they reach production. It runs in under 5 seconds as a git hook."
      },
      {
        q: "What is semantic drift?",
        a: "Semantic drift is when code changes still compile and pass tests but silently alter behavior — authorization logic, invariants, contracts, or business rules. Traditional linters miss it."
      },
      {
        q: "How is HefestoAI different from SonarQube or Snyk?",
        a: "HefestoAI is pre-commit (prevents issues before they enter the repo). SonarQube and Snyk are post-commit scanners that detect issues after the fact. HefestoAI is also designed specifically for AI-generated code."
      },
      {
        q: "How is HefestoAI different from Claude Code Security?",
        a: "Claude Code Security scans entire repos post-commit for security vulnerabilities (Enterprise only). HefestoAI runs pre-commit for any developer at $0-19/month, focusing on code quality and semantic drift."
      },
      {
        q: "How do I install HefestoAI?",
        a: "pip install hefesto-ai — requires Python 3.10+. Then run: hefesto analyze . or hefesto install-hooks to auto-run on every commit."
      },
      {
        q: "What languages does HefestoAI support?",
        a: "17 programming languages including Python, JavaScript, TypeScript, Java, Go, Rust, and more."
      },
      {
        q: "What does HefestoAI cost?",
        a: "FREE: $0/month (basic analysis, 17 languages). PRO: $8/month (advanced analysis, CI/CD, REST API). OMEGA: $19/month (full suite, production monitoring). 14-day free trial, no credit card required."
      },
      {
        q: "Is there a founding member discount?",
        a: "Yes — first 25 customers get permanent 40% discount with code FOUNDING100. PRO becomes $4.80/month, OMEGA becomes $11.40/month."
      },
      {
        q: "Can I use HefestoAI with Claude Code / Copilot / Cursor?",
        a: "Yes — HefestoAI works as a pre-commit hook in any git workflow. It is specifically designed to validate code generated by Claude Code, GitHub Copilot, Cursor, and other AI assistants."
      },
      {
        q: "Does HefestoAI send my code to any server?",
        a: "No. Analysis runs 100% locally on your machine. Your code never leaves your device."
      },
      {
        q: "Is HefestoAI open source?",
        a: "The core is open source (MIT). PRO and OMEGA tiers include closed-source ML enhancements."
      },
      {
        q: "How do I add HefestoAI as an MCP tool?",
        a: "npx @smithery/cli@latest mcp add artvepa80/hefestoai — works with Claude Code, Cursor, and any MCP-compatible client."
      },
      {
        q: "Where is HefestoAI built?",
        a: "Lima, Peru — by Arturo Velasquez via Narapa LLC (Miami). Independent founder, not VC-backed."
      }
    ],
    endpoints: {
      mcp: "https://hefestoai.narapallc.com/api/mcp-protocol",
      ask: "https://hefestoai.narapallc.com/api/ask",
      openapi: "https://hefestoai.narapallc.com/api/openapi.json"
    }
  });
}
