name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Lint with black
      run: |
        black --check hefesto/ tests/

    - name: Type check with mypy
      run: |
        mypy hefesto/ iris/ omega/ --ignore-missing-imports || true

    - name: Run unit tests (skip cloud/integration tests)
      run: |
        pytest -m "not requires_gcp and not requires_stripe and not integration" -v --cov=hefesto --cov-report=xml --cov-report=term
      env:
        # Tests run without cloud credentials - cloud tests are skipped
        CI: true
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.python-version }}

  # Optional: Integration tests with cloud services
  # Uncomment to run full test suite with GCP/Stripe credentials
  # integration-tests:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: "3.10"
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       pip install -r requirements-dev.txt
  #   - name: Run all tests including cloud integration
  #     run: |
  #       pytest tests/ -v --cov=hefesto --cov-report=xml
  #     env:
  #       GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  #       GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  #       STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort flake8

    - name: Check formatting
      run: |
        black --check .
        isort --check .

    - name: Lint
      run: |
        flake8 hefesto/ --max-line-length=100 --extend-ignore=E203,W503

  docs-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check standard emails in documentation
      run: |
        echo "Checking for non-standard email addresses in documentation..."
        if grep -rIn --exclude-dir=.git --exclude-dir=venv --exclude-dir=htmlcov --include="*.md" -E "[A-Za-z0-9._%+-]+@narapa\.ai" . ; then
          echo "❌ Found @narapa.ai emails. Use support@narapallc.com or contact@narapallc.com instead."
          exit 1
        fi
        if grep -rIn --exclude-dir=.git --exclude-dir=venv --exclude-dir=htmlcov --include="*.md" "security@narapallc\.com" . ; then
          echo "❌ Found security@narapallc.com. Use support@narapallc.com instead."
          exit 1
        fi
        if grep -rIn --exclude-dir=.git --exclude-dir=venv --exclude-dir=htmlcov --include="*.md" "sales@narapallc\.com" . ; then
          echo "❌ Found sales@narapallc.com. Use contact@narapallc.com instead."
          exit 1
        fi
        echo "✅ All documentation uses standard emails (support@narapallc.com, contact@narapallc.com)"

